### PR TITLE
Fix profile pictures not appearing on initial run

### LINKED ISSUE #62: Profile picture placeholders missing
**What happens**: When CliniCal is initially run, the app runs with no profile pictures.
image

**What is supposed to happen**: A placeholder profile picture is supposed to be implemented on the left of every entry.

**Caused by**: The app looks for `data/stock_picture.png` but it is unable to find the image.

### PR DESCRIPTION
**Pull request by ktaekwon000**
Closes https://github.com/AY2021S1-CS2103T-W11-4/tp/issues/62.

### CODE REVIEW

**Comment by ktaekwon000** [comment]
Don't approve this yet! I just realised that this code still generates the file even when the file is already present.

**Comment by ktaekwon000** [comment]
Pushed a fix regarding the issue above. 

This implementation also allows the user to edit the default profile picture to something of their choice, by editing `data/stock_picture.png`. If the user wants to return to the default profile picture, they can just delete `data/stock_picture.png` and the app will automatically regenerate the file on the next run.

I'm not sure if this should be added into the User Guide, since it's a niche use case.

**Comment by afroneth** [comment]
LGTM!

**Review by afroneth — APPROVED** [review]

**Comment by Michaeliaaa** [comment]
LGTM!

**Pull request merged**
