### PR TITLE
Add styling for Tabs & welcome message

### PR DESCRIPTION
**Pull request by eugene3231**
java_XP6BR6ENuS

### CODE REVIEW

**Review by gsmoon97 — APPROVED** [review]
LGTM! One thing though. I was thinking maybe it's better to just say "Before you get started, type help to find out how to use CliniCal." or something along those lines. Cause I think it might be bit confusing for some users if the first thing they see are the commands without any description on what they actually do. Other than that, the welcoming message idea looks solid!

**Comment by afroneth** [comment]
Is there a way to partition the tabs so that there is a clearer distinction? I drew a rough sketch below.

Untitled

**Comment by Michaeliaaa** [comment]
I agree with Kenneth. I prefer having clearer borders for tabs as well. I think making the unselected tab looked darker in fill would be nicer.

**Comment by eugene3231** [comment]
I could only add in some borders for the tab currently selected so like this, however not sure if it looks abit clunky...
And I couldn't find any documentation on how to change the unselected tab styling (making it darker etc)

java_kndwGXNLdd


OR

java_xdKaxOQGyg

**Comment by Michaeliaaa** [comment]
For the tab borders, the colours are the same except for the bottom side. It may come across as less appealing to me so I think it is good to make it the same colour. Just a suggestion.

**Pull request merged**
