### PR TITLE
Fix bugs #189, #206, #214, #219 + PPP

### LINKED ISSUE #189: [PE-D] App does not respond when adding appointments with minutes with a positive decimal number
Steps to replicate
1. Start with a patient list of only 2 items
2. Run addappt 2 st/2020-10-29 13:00 d/0.5

Note: The response in the box is from a previous command.

* You can run any command prior in this example I ran list, but once you run run addappt 2 st/2020-10-29 13:00 d/0.5 the app no longer responds

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: orzymandias/ped#5

### PR DESCRIPTION
**Pull request by Michaeliaaa**
Fix #189, #206, #214 , #219

### CODE REVIEW

**Comment by Michaeliaaa** [comment]
Do not merge yet. I will need to modify mine after Moon's.

**Comment by Michaeliaaa** [comment]
I realised when I merged Moon's PR to work on the modifications, the format is still following the old one so I updated the format here.

**Review by gsmoon97 — APPROVED** [review]
Hey Michaelia! The pr looks great. There's just one more thing to note about the AppointmentDateTime. Currently, AppointmentDateTime also accepts years beyond 19XX and 2XXX. Also, technically 30 or 31 might not be a valid input for day, depending on the month. So I was thinking you could maybe revert the changes from lines 17 to 21.

**Comment by Michaeliaaa** [comment]
> Hey Michaelia! The pr looks great. There's just one more thing to note about the AppointmentDateTime. Currently, AppointmentDateTime also accepts years beyond 19XX and 2XXX. Also, technically 30 or 31 might not be a valid input for day, depending on the month. So I was thinking you could maybe revert the changes from lines 17 to 21.

I forgot about it, lemme do amendments to it.

**Pull request merged**
